// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: LED

#include "../ui.h"

lv_obj_t * ui_Index = NULL;
lv_obj_t * ui_led_switch = NULL;
lv_obj_t * ui_led_switch_label = NULL;
// event funtions

// build funtions

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_led_switch = lv_switch_create(ui_Index);
    lv_obj_set_width(ui_led_switch, 94);
    lv_obj_set_height(ui_led_switch, 50);
    lv_obj_set_x(ui_led_switch, 0);
    lv_obj_set_y(ui_led_switch, 10);
    lv_obj_set_align(ui_led_switch, LV_ALIGN_CENTER);

    ui_led_switch_label = lv_label_create(ui_Index);
    lv_obj_set_width(ui_led_switch_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_led_switch_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_led_switch_label, 0);
    lv_obj_set_y(ui_led_switch_label, -36);
    lv_obj_set_align(ui_led_switch_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_led_switch_label, "LED IO12");
    lv_obj_set_style_text_color(ui_led_switch_label, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_led_switch_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_led_switch_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Index_screen_destroy(void)
{
    if(ui_Index) lv_obj_del(ui_Index);

    // NULL screen variables
    ui_Index = NULL;
    ui_led_switch = NULL;
    ui_led_switch_label = NULL;

}
