// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: LED

#ifndef UI_INDEX_H
#define UI_INDEX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Index
extern void ui_Index_screen_init(void);
extern void ui_Index_screen_destroy(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_led_switch;
extern lv_obj_t * ui_led_switch_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

