; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4_r3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip#55.03.312-1
board = esp32-p4
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_unflags = -Os
build_flags = 
  -I./include
  ; -Ilib/lvgl/demos
  ; -Ilib
  ; -DLV_LVGL_H_INCLUDE_SIMPLE
  -DCORE_DEBUG_LEVEL=5
  -O3
  -DARDUINO_LOOP_STACK_SIZE=32768
build_src_filter =
  +<*>
  ; Force compile LVGL demo, remove when working on your own project
  ; +<C:\Users\sonth\GitHub\ATD5-P4-Test\lib\lvgl\demos>
monitor_filters = esp32_exception_decoder
monitor_eol = LF
board_build.partitions = partitions.csv
board_upload.flash_size = 32MB
